### ISSUE TITLE
Unable to Login / Download

### ISSUE THREAD

**Issue by ab-cc** [Valyreon/Subloader#25]
Thank you for the wonderful program, the simplicity and polished UI makes this such a great app.

The latest release (SubloaderV160Portable.exe) is giving error on trying to login:
![image](https://github.com/Valyreon/Subloader/assets/45005187/b86c1dd8-12fb-4f3b-8fd9-27a0dd5d62f2)

Same issue with respect to Subtitle Search:
![image](https://github.com/Valyreon/Subloader/assets/45005187/2d41393d-2443-498e-b0d1-4751bf258c9f)

Kindly give info on how to fix this please.

**Comment by ab-cc** [comment]
The command line interface is also not working:
![image](https://github.com/Valyreon/Subloader/assets/45005187/761d7920-7ece-441c-9b17-e0a2aae722b7)

**Comment by Valyreon** [comment]
Hi, this error will appear if the app for any reason can't connect the the opensubtitles API.

This is probably an issue on your network side. Opensubtitles is blocked by some internet providers in certain countries like Norway and others. If you are using VPN, it may be due to the chosen server's location or their internet provider etc.

I can see in the OS API stats page that there are daily users and for me it works fine.

**Comment by ab-cc** [comment]
Thank you for your response, however I am not behind VPN and I am able to connect to https://www.opensubtitles.com/en in browser without any issues. I'm also able to connect to https://api.opensubtitles.com/api/v1/download via Postman. I will check firewall settings to be sure the app is being allowed.

**Comment by ab-cc** [comment]
I do confirm this was an issue with firewall, thanks a lot @Valyreon 

A suggestion: If the error message can be indicative of a connectivity issue / self-explanatory, it would make it easy for troubleshooting. The current error message of "Something went wrong. Please try again" doesn't give any indicators on what might be going wrong. Hope this can be added.
